### ISSUE TITLE
Infix Operator Tracking Issue

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#594]
(Making a tracking issue so I don't forget!)

- [ ] Create typeclasses for all the typical infix operators (#451)
- [ ] Make infix operator syntax forward to the typeclass methods
- [ ] Change infix operators to use a single production that resolves associativity and precedence while forwarding ("custom operator infrastructure")
- [ ] Make infix operators a non-interfering extension?
- [ ] Expose custom infix operators to users? (Discuss me!)
- [ ] Idiom brackets? (`[| f x1 x2 x3 |]` => `ap(ap(map(f, x1), x2), x3)`) Not hugely related, but replaces some of the need for:
- [ ] Traditional operators for Haskellism (`<$>`, `<*>`, `>>=`, `>=>`, `$>`, `*>`, etc.)
  - If we add these, I promise to write a doc page about them, with a spoken name (e.g. `applyFirst`), the definition in terms of typeclass methods, the definition in terms of `do` where possible, and an example of use; someone else should come up with a better term than "Haskellism," though.
